version: '3'

services:
  config-server:
    build: misy2-config-server
    image: misy2/config-server
    container_name: config
    ports:
    - "8888:8888"

  discovery-server:
    build: misy2-discovery-server
    image: misy2/discovery-server
    container_name: discovery
    depends_on:
      - config-server
    ports:
    - "8761:8761"
    environment:
      WAIT_HOSTS: config:8888
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  gateway-server:
    build: misy2-gateway-server
    image: misy2/gateway-server
    container_name: gateway
    depends_on:
      - config-server
      - discovery-server
    ports:
    - "8085:8085"
    environment:
      WAIT_HOSTS: config:8888, discovery:8761
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  greeting-service1:
    build: misy2-greeting-service
    image: misy2/greeting-service
    container_name: greeting1
    depends_on:
      - config-server
    environment:
      WAIT_HOSTS: config:8888
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  orders-service1:
    build: misy2-orders-service
    image: misy2/orders-service
    container_name: orders1
    depends_on:
      - config-server
    environment:
      WAIT_HOSTS: config:8888
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  users-service1:
    build: misy2-users-service
    image: misy2/users-service
    container_name: users1
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
    environment:
      WAIT_HOSTS: config:8888, discovery:8761, gateway:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  users-service2:
    build: misy2-users-service
    image: misy2/users-service
    container_name: users2
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
    environment:
      WAIT_HOSTS: config:8888, discovery:8761, gateway:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1