version: '3'

services:
  config-server:
    build: misy2-config-server
    image: misy2/config-server
    container_name: config
    ports:
    - "8888:8888"

  discovery-server:
    build: misy2-discovery-server
    image: misy2/discovery-server
    container_name: discovery
    depends_on:
      - config-server
    ports:
    - "8761:8761"
    environment:
      WAIT_HOSTS: config:8888
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  gateway-server:
    build: misy2-gateway-server
    image: misy2/gateway-server
    container_name: gateway
    depends_on:
      - config-server
      - discovery-server
    ports:
    - "8080:8080"
    environment:
      WAIT_HOSTS: config:8888, discovery:8761
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  users-service1:
    build: misy2-users-service
    image: misy2/users-service
    container_name: users1
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
    environment:
      WAIT_HOSTS: config:8888, discovery:8761, gateway:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60

  users-service2:
    build: misy2-users-service
    image: misy2/users-service
    container_name: users2
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
    environment:
      WAIT_HOSTS: config:8888, discovery:8761, gateway:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 60